# Data Structures

In [1]:
import numpy as np
import pandas as pd

For most of this course we are going to work with `pandas` DataFrames. However, it's important to start with an introduction to the different types of data structures available in Python, their characteristics, their differences and their comparative advantages.

One can categorize data structures in Python as follows:

- lists
- tuples
- sets
- dictionaries
- numpy arrays
- pandas DataFrames
- pyspark DataFrames

## Lists: mutable dynamic arrays

A **list** is a mutable array data structure in Python with the following characteristics:

- can hold any type of data
- can hold different types of data at the same time
- can be modified
- 

Lists are generated using square brackets.

In [2]:
l = [12, "world", [3,4,5]]
print(l)

[12, 'world', [3, 4, 5]]


We modify elements by calling the index of the list.

In [3]:
l[0] = 'hello'
print(l)

['hello', 'world', [3, 4, 5]]


We add elements to a list using `.append()`.

In [4]:
l.append(23)
l

['hello', 'world', [3, 4, 5], 23]

We can remove elements by calling `del` on it.

In [5]:
del l[0]
print(l)

['world', [3, 4, 5], 23]


We can combine two lists using `+`. Note that this operation does not modify the list but generates a new one.

In [6]:
l + [23]

['world', [3, 4, 5], 23, 23]

We can also generate lists using comprehensions.

In [7]:
l = [n for n in range(3)]
print(l)

[0, 1, 2]


Comprehensions are a powerful tool!

In [8]:
l = [n+10 for n in range(10) if (n%2==0) and (n>4)]
print(l)

[16, 18]


## Tuples: immutable dynamic arrays

A **tuple** is an immutable array data structure in Python with the following characteristics:

- can hold any type of data
- can hold different types of data at the same time
- **can not be modified**
- 

Tuples are generated using curve brackets.

In [9]:
# A list of different data types
t = (12, "world", [3,4,5])
print(t)

(12, 'world', [3, 4, 5])


We *cannot* modify tuples!

In [10]:
# Try to modify element
try:
    t[0] = 'hello'
except Exception as e:
    print(e)

'tuple' object does not support item assignment


In [11]:
# Try to add element
try:
    t.append('hello')
except Exception as e:
    print(e)

'tuple' object has no attribute 'append'


In [12]:
# Try to remove element
try:
    del t[0]
except Exception as e:
    print(e)

'tuple' object doesn't support item deletion


We can combine two tuples using `+`. Note that this operation does not modify the tuple but generates a new one. Also note that to generate a 1-element tuple we need to insert a comma.

In [13]:
t + (23,)

(12, 'world', [3, 4, 5], 23)

We can generate tuples using comprehensions, but we need to specify it's a `tuple`.

In [14]:
t = tuple(n for n in range(3))
print(t)

(0, 1, 2)


## Sets: unordered unique collections

A **set** is a mutable array data structure in Python with the following characteristics:

- **can only hold hashable types**
- can hold different types of data at the same time
- **cannot be modified**
- **cannot contain duplicates**

Sets are generated using curly brackets.

In [15]:
s = {12, "world", (3,4,5)}
print(s)

{'world', (3, 4, 5), 12}


We *cannot* modify sets!

In [16]:
# Try to modify element
try:
    s[0] = 'hello'
except Exception as e:
    print(e)

'set' object does not support item assignment


But we can add elements using `.add()`.

In [17]:
s.add('hello')
print(s)

{'world', (3, 4, 5), 12, 'hello'}


However, we cannot add duplicates.

In [18]:
s.add('hello')
print(s)

{'world', (3, 4, 5), 12, 'hello'}


We cannot delete elements of a set.

In [19]:
# Try to remove element
try:
    del s[0]
except Exception as e:
    print(e)

'set' object doesn't support item deletion


We can also generate sets using comprehensions.

In [20]:
s = {n for n in range(3)}
print(s)

{0, 1, 2}


## Dictionaries: named lists

A **dictionary** is a mutable array data structure in Python with the following characteristics:

- can hold any type of data
- can hold different types of data at the same time
- can be modified
- **items are named**

Dictionaries are generated using curly brackets. Since elements are indexed by keys, we have to provide one for each element.

Dictionary keys can be of any **hashable type**. A hashable object has a hash value that never changes during its lifetime, and it can be compared to other objects. Hashable objects that compare as equal must have the same hash value.

Immutable types like strings and numbers are hashable and work well as dictionary keys. You can also use tuple objects as dictionary keys as long as they contain only hashable types themselves.

In [21]:
d = {"first": 12, 2: "world", (3,): [3,4,5]}
print(d)

{'first': 12, 2: 'world', (3,): [3, 4, 5]}


We modify elements by calling the corresponding key of the dictionary.

In [22]:
d["first"] = 'hello'
print(d)

{'first': 'hello', 2: 'world', (3,): [3, 4, 5]}


We cannot use indexes! The argument inside the square brackets is interpreted as a key. If the key does not currently exist, it is added.

In [23]:
d[0] = 'hello'
print(d)

{'first': 'hello', 2: 'world', (3,): [3, 4, 5], 0: 'hello'}


We can remove elements by calling `del` on it.

In [24]:
del d[0]
print(d)

{'first': 'hello', 2: 'world', (3,): [3, 4, 5]}


We can cannot combine two dictionaries using `+`.

In [25]:
try:
    d + {"fourth": (1,2)}
except Exception as e:
    print(e)

unsupported operand type(s) for +: 'dict' and 'dict'


We can also generate dictionaries using comprehensions.

In [26]:
d = {f"k{n}": n+1 for n in range(3)}
print(d)

{'k0': 1, 'k1': 2, 'k2': 3}


We can access values of the dictionary using `.values()`.

In [27]:
d.values()

dict_values([1, 2, 3])

We can access keys of the dictionary using `.keys()`.

In [28]:
d.keys()

dict_keys(['k0', 'k1', 'k2'])

## Numpy array

A **numpy array** is a mutable array data structure in Python with the following characteristics:

- can hold any type of data
- **can only hold one type at the same time**
- can be modified
- **can be multi-dimensional**
- **support matrix operations**

Numpy arrays are generated the `np.array()` function on a list.

In [29]:
a = np.array([1,2,3])
print(a)

[1 2 3]


We can make 2-dimensional arrays (a matrix) as lists of lists.

In [30]:
m = np.array([[1,2,3] , [4,5,6]])
print(m)

[[1 2 3]
 [4 5 6]]


We modify elements by calling the index of the numpy array.

In [31]:
m[0,0] = 89
print(m)

[[89  2  3]
 [ 4  5  6]]


We can check the shape using `.shape`

In [32]:
m.shape

(2, 3)

We can expand dimensions using `.expand_dims()`.

In [33]:
a = np.expand_dims(a,1)
print(a)

[[1]
 [2]
 [3]]


We can transpose matrices using `.T`.

In [34]:
a = a.T
print(a)

[[1 2 3]]


We add elements to a list using `np.concatenate()`.

In [35]:
m = np.concatenate((m, a), axis=0)
print(m)

[[89  2  3]
 [ 4  5  6]
 [ 1  2  3]]


We cannot remove elements of numpy arrays.

In [36]:
try:
    del a[0]
except Exception as e:
    print(e)

cannot delete array elements


We can do matrix operations between numpy arrays. For example, we can do multiplication with `@`.

In [37]:
a @ m

array([[100,  18,  24]])

If we use `*` we get dot (or element-wise) multiplication instead.

In [38]:
a * m

array([[89,  4,  9],
       [ 4, 10, 18],
       [ 1,  4,  9]])

There is a wide array of functions available in numpy. For example `np.invert()` inverts a squared matrix.

In [39]:
np.invert(m)

array([[-90,  -3,  -4],
       [ -5,  -6,  -7],
       [ -2,  -3,  -4]])

## Comparison

Which data structure should you use and why? Let's compare different data types

In [40]:
K = 100_000
l = [n for n in range(K)]
t = tuple(n for n in range(K))
s = {n for n in range(K)}
a = np.array([n for n in range(K)])

**Size**

Which data type is more efficient?

In [41]:
import sys

def compare_size(list_objects):
    for o in list_objects:
        print(f"Size of {type(o)}: {sys.getsizeof(o)}")

In [42]:
compare_size([l, t, s, a])

Size of <class 'list'>: 800984
Size of <class 'tuple'>: 800040
Size of <class 'set'>: 4194520
Size of <class 'numpy.ndarray'>: 800104


Size is very similar for lists, tuples and numpy arrays.

**Speed**

Which data type is faster?

In [71]:
import time

def compare_time(list_objects):
    for o in list_objects:
        start = time.time()
        [x**2 for x in o]
        end = time.time()
        print(f"Time of {type(o)}: {end - start}")

In [72]:
compare_time([l, t, s, a])

Time of <class 'list'>: 0.0464017391204834
Time of <class 'tuple'>: 0.03342103958129883
Time of <class 'set'>: 0.022654056549072266
Time of <class 'numpy.ndarray'>: 0.010206937789916992


Numpy arrays are faster at math operations.